### ISSUE TITLE
write down concept for masymos-seek-middleware

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-seek-middleware#1]
# ToDo
- [x] create masymos-seek-related documentation apart from the masymos docs
- [x] mapping table, acitivity diagram, sequence diagram - to show dataflow, push, pull, hooks, requests,…
- [x] write down decisions so far
- [x] write down general concept and requirements

@ronhenkel
