### ISSUE TITLE
simplify MaSeMiWa Workflow

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-seek-middleware#10]
# Overview
- use a Queue in MaSeMiWa to handle all INSERT/UPDATES
- use a Thread handling the Queue
- provide a status-interface

# ToDo
- [x] update sequence UML
- [x] update activity UML
- [x] check/update docs: decisions and QnA
