### ISSUE TITLE
save model version on import

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-seek-middleware#16]
# Overview
- model version is ignored for now
- Morre can handle a models version

# ToDo
- [ ] extract model version from SEEK metadata with the Middleware
- [ ] provide it on INSERT (by middleware)
- [ ] think about a real UPDATE with checking the version beforehand (by middelware)
- [ ] check Morre's add/remove functions for use with the version as check parameter
