### ISSUE TITLE
get overview about the model link types in fairdomhub

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-seek-middleware#7]
# Overview
- see #5 - model-links are not checked by SEEK

# ToDo
- [x] check and count models model file (check mime)
- [x] check, how to use the "maybe"-MIME models → **moved maybe-MIMEs to valid MIMEs**
- [x] check, how many models have more then one valid model link → **6**
- [x] recheck supported levels and versions (SBML, SELLML, SEDML) → **[docs](https://masemiwa.readthedocs.io/en/latest/dev_qna.html#supported-model-types-sbml-cellml-sedml)**
- [x] find a decision to deal with differences in level/version from namespaces vs. attribute → **ignore file!**
    - [SBML Validator](http://constraint.caltech.edu:8888/validator_servlet/index.jsp) also says: Differences here mean invalid SBML

# Results (16.09.2020)
* counters (versions by namespace for valid MIME ('application/sbml+xml', 'application/xml', 'text/xml'))
```
'http://www.sbml.org/sbml/level2/version4'       →    71
'http://www.sbml.org/sbml/level3/version1/core'  →    40
'http://www.sbml.org/sbml/level2'                →    17
'http://www.copasi.org/static/schema'            →    13
'http://www.sbml.org/sbml/level2/version3'       →    13
'http://sbgn.org/libsbgn/pd/0.1'                 →    5
'http://www.sbml.org/sbml/level2/version2'       →    1
```
* counters (metadata from json)
```
Number of public models: 334
Number of models with fairdomhub.org-content in link-field: 333
Number of models with non-fairdomhub.org-content in link-field: 0
Number of models without fairdomhub.org-content in any link-field: 0
Number of models without content_blobs: 1
Number of models with valid MIME¹: 187
Number of models with maybe MIME¹: 0
Number of models with invalid MIME¹: 146
Number of models with more then one MIME-valid content: 6: ['225', '231', '269', '325', '326', '734']
Number of MIME-valid models (usable by MaSyMoS): 187

¹MIME-overview:
- valid MIME: ('application/sbml+xml', 'application/xml', 'text/xml')
- maybe MIME: ()
- invalid MIME: ('namespace', 'application/gzip', 'application/json', 'application/mathematica', 'application/matlab', 'application/octet-stream', 'application/pdf', 'application/x-compressed-tar', 'application/x-rar', 'application/x-ruby', 'application/x-tar', 'application/xhtml+xml', 'application/zip', 'image/png', 'text/html', 'text/plain', 'text/x-python', 'text/x-uuencode', 'text/nlogo')
```
* mime types (all existing)
```
application/gzip
application/json
application/mathematica
application/matlab
application/octet-stream
application/pdf
application/sbml+xml
application/x-compressed-tar
application/xhtml+xml
application/xml
application/x-rar
application/x-ruby
application/x-tar
application/zip
image/png
text/html
text/nlogo
text/plain
text/xml
text/x-python
text/x-uuencode
```

:information_source: @ronhenkel
